import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase.server'
import { getUser, badRequest, serverError, unauthorized } from '@/lib/api'
import { createOrderSchema } from '@/lib/validation'
import { computeTotals } from '@/lib/pricing'
import { isRazorpayConfigured, razorpay } from '@/lib/razorpay'
import { orderDeliveryMode } from '@/lib/shipping'

export async function GET(req: NextRequest) {
  const user = await getUser(req)
  if (!user) return unauthorized()

  const { data, error } = await supabaseAdmin
    .from('orders')
    .select('*')
    .eq('user_id', user.id)
    .order('created_at', { ascending: false })

  if (error) return serverError(error, 'Failed to load orders')
  return NextResponse.json(data)
}

export async function POST(req: NextRequest) {
  const user = await getUser(req)

  let body: unknown
  try {
    body = await req.json()
  } catch {
    return badRequest('Malformed request body')
  }

  const parsed = createOrderSchema.safeParse(body)
  if (!parsed.success) return badRequest(parsed.error.issues[0]?.message ?? 'Invalid order')
  const input = parsed.data

  // Guests must be contactable (mirrors the orders_contact_check DB constraint)
  if (!user && (!input.guest_name || !input.guest_phone)) {
    return badRequest('Guest name and phone are required')
  }

  if (!isRazorpayConfigured()) {
    return NextResponse.json({ error: 'Online payments are not set up yet' }, { status: 503 })
  }

  // Authoritative pricing — never trust client-sent money. Look up live prices
  // from the DB and rebuild every line item server-side. Stock is NOT consumed
  // here; it's consumed only once payment succeeds.
  const ids = input.items.map(i => i.id)
  const { data: products, error: prodErr } = await supabaseAdmin
    .from('products')
    .select('id, name, price, in_stock, allow_backorder, delivery_type, net_weight_grams')
    .in('id', ids)

  if (prodErr) return serverError(prodErr, 'Failed to validate cart')

  const byId = new Map((products ?? []).map(p => [p.id, p]))
  const lineItems = []
  for (const item of input.items) {
    const p = byId.get(item.id)
    if (!p) return badRequest('One or more items are no longer available')
    if (!p.in_stock && !p.allow_backorder) return badRequest(`Sold out: ${p.name}`)
    lineItems.push({
      id: p.id,
      name: p.name,
      qty: item.qty,
      price: p.price,
      net_weight_grams: p.net_weight_grams ?? undefined,
      delivery_type: p.delivery_type,  // snapshot — drives hyperlocal no-cancel + courier routing
      ...(item.flavour ? { flavour: item.flavour } : {}),
    })
  }

  // Fulfilment routing: a cart is single-mode; hyperlocal must ship to a serviceable Mumbai pincode.
  const delivery_mode = orderDeliveryMode(lineItems)
  if (delivery_mode === 'mixed') {
    return badRequest('Your cart mixes same-day and standard items — please order them separately')
  }
  if (delivery_mode === 'hyperlocal') {
    const { data: pin } = await supabaseAdmin
      .from('hyperlocal_pincodes').select('pincode').eq('pincode', input.address.pin).maybeSingle()
    if (!pin) return badRequest('Same-day items deliver within Mumbai only — please use a serviceable pincode')
  }

  const subtotal = lineItems.reduce((a, i) => a + i.price * i.qty, 0)
  // discount stays 0 until coupons ship; baked into the formula now.
  const { delivery_fee, discount, total } = computeTotals(subtotal, 0)

  // id is generated by the DB (sequence default) — never client-supplied.
  const { data: created, error } = await supabaseAdmin
    .from('orders')
    .insert({
      user_id: user?.id ?? null,
      guest_name: input.guest_name ?? null,
      guest_phone: input.guest_phone ?? null,
      guest_email: input.guest_email ?? null,
      items: lineItems,
      subtotal,
      delivery_fee,
      discount,
      coupon_code: null,
      total,
      address: input.address,
      delivery_mode,
      payment_method: 'razorpay',
      payment_status: 'pending',
      status: 'Pending',
    })
    .select('id, total')
    .single()

  if (error) return serverError(error, 'Failed to place order')

  // Create the matching Razorpay order; the modal charges this amount.
  try {
    const rzpOrder = await razorpay().orders.create({
      amount: total * 100,        // paise
      currency: 'INR',
      receipt: created.id,
    })
    await supabaseAdmin.from('orders').update({ razorpay_order_id: rzpOrder.id }).eq('id', created.id)

    return NextResponse.json({
      id: created.id,
      razorpay: { orderId: rzpOrder.id, amount: total * 100, keyId: process.env.RAZORPAY_KEY_ID },
    })
  } catch (e) {
    return serverError(e, 'Could not start payment')
  }
}
