import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase.server'
import { getUser, badRequest, serverError, unauthorized } from '@/lib/api'
import { createOrderSchema } from '@/lib/validation'
import { computeTotals } from '@/lib/pricing'

export async function GET(req: NextRequest) {
  const user = await getUser(req)
  if (!user) return unauthorized()

  const { data, error } = await supabaseAdmin
    .from('orders')
    .select('*')
    .eq('user_id', user.id)
    .order('created_at', { ascending: false })

  if (error) return serverError(error, 'Failed to load orders')
  return NextResponse.json(data)
}

export async function POST(req: NextRequest) {
  const user = await getUser(req)

  let body: unknown
  try {
    body = await req.json()
  } catch {
    return badRequest('Malformed request body')
  }

  const parsed = createOrderSchema.safeParse(body)
  if (!parsed.success) return badRequest(parsed.error.issues[0]?.message ?? 'Invalid order')
  const input = parsed.data

  // Guests must be contactable (mirrors the orders_contact_check DB constraint)
  if (!user && (!input.guest_name || !input.guest_phone)) {
    return badRequest('Guest name and phone are required')
  }

  // Authoritative pricing — never trust client-sent money. Look up live prices
  // from the DB and rebuild every line item server-side.
  const ids = input.items.map(i => i.id)
  const { data: products, error: prodErr } = await supabaseAdmin
    .from('products')
    .select('id, name, price, in_stock, allow_backorder')
    .in('id', ids)

  if (prodErr) return serverError(prodErr, 'Failed to validate cart')

  const byId = new Map((products ?? []).map(p => [p.id, p]))
  const lineItems = []
  const consumed: { id: string; qty: number }[] = []
  for (const item of input.items) {
    const p = byId.get(item.id)
    if (!p) return badRequest('One or more items are no longer available')
    // Manual hard-stop only: product explicitly hidden with backorders off.
    if (!p.in_stock && !p.allow_backorder) return badRequest(`Sold out: ${p.name}`)

    // Consume today's stock; any shortfall is baked & shipped later (advisory —
    // orders are never blocked on quantity).
    const { data: shortfall } = await supabaseAdmin.rpc('consume_stock', { p_id: p.id, p_qty: item.qty })
    const short = typeof shortfall === 'number' ? shortfall : 0
    const fromStock = item.qty - short
    if (fromStock > 0) consumed.push({ id: p.id, qty: fromStock })

    lineItems.push({
      id: p.id,
      name: p.name,
      qty: item.qty,
      price: p.price,
      is_preorder: short > 0,
      ...(short > 0 ? { preorder_qty: short } : {}),
    })
  }

  const subtotal = lineItems.reduce((a, i) => a + i.price * i.qty, 0)
  const { delivery_fee, total } = computeTotals(subtotal)

  // id is generated by the DB (sequence default) — never client-supplied.
  const { data: created, error } = await supabaseAdmin
    .from('orders')
    .insert({
      user_id: user?.id ?? null,
      guest_name: input.guest_name ?? null,
      guest_phone: input.guest_phone ?? null,
      guest_email: input.guest_email ?? null,
      items: lineItems,
      subtotal,
      delivery_fee,
      total,
      address: input.address,
      payment_method: input.payment_method,
      payment_status: 'pending',
      status: 'Pending',
    })
    .select('id, total')
    .single()

  if (error) return serverError(error, 'Failed to place order')

  // Audit the stock consumed by this order (best-effort; the counter is already
  // authoritative via consume_stock).
  if (consumed.length > 0) {
    await supabaseAdmin.from('stock_movements').insert(
      consumed.map(c => ({ product_id: c.id, delta: -c.qty, reason: 'order', ref: created.id })),
    )
  }

  return NextResponse.json({ id: created.id, total: created.total })
}
